global:
  sendAnonymousUsage: false

api:
  dashboard: false
  insecure: false

log:
  level: INFO
  format: common

entryPoints:
  web:
    address: 127.0.0.1:8081

providers:
  file:
    directory: ./proxy
